version: '3'

services:
  app:
    build:
      context: node-app
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node-app:/usr/src/app
    tty: true
    command: ["node", "/usr/src/app/index.js"]
  nginx:
    build:
      context: nginx-app
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    

networks:
  node-network:
    driver: bridge